Netgen\Layouts\Contentful\Entity\ContentfulEntry:
    type: entity
    table: contentful_entry
    manyToMany:
        routes:
            targetEntity: Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Orm\Route
            cascade: ['persist', 'remove']
    id:
        id:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
        json:
            type: text
        isPublished:
            type: boolean
        isDeleted:
            type: boolean
            nullable: true
