services:
    netgen_layouts.contentful.block.block_definition_handler.entry_field:
        class: Netgen\Layouts\Contentful\Block\BlockDefinition\Handler\EntryFieldHandler
        arguments:
            - "@netgen_layouts.contentful.service"
            - "@request_stack"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler, identifier: contentful_entry_field }
