services:
    netgen_layouts.contentful.block.block_definition_handler.entry_field:
        class: Netgen\Layouts\Contentful\Block\BlockDefinition\Handler\EntryFieldHandler
        arguments:
            - "@netgen_layouts.contentful.service"
            - "@request_stack"
            - "@netgen_layouts.contentful.rich_text_parser"
            - "@netgen_layouts.item.item_builder"
        tags:
            - { name: netgen_layouts.block_definition_handler, identifier: contentful_entry_field }
