services:
    netgen_layouts.contentful.controller.contenful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Controller\ContentfulController
        public: true
        parent: netgen_layouts.controller.base
        deprecated: 'The "%service_id%" service is deprecated. Use "netgen_layouts.contentful.controller.view" or "netgen_layouts.contentful.controller.webhook" instead'
        arguments:
            - "@netgen_layouts.contentful.service"

    netgen_layouts.contentful.controller.view:
        class: Netgen\Bundle\LayoutsContentfulBundle\Controller\ViewController
        public: true
        parent: netgen_layouts.controller.base

    netgen_layouts.contentful.controller.webhook:
        class: Netgen\Bundle\LayoutsContentfulBundle\Controller\WebhookController
        public: true
        parent: netgen_layouts.controller.base
        arguments:
            - "@netgen_layouts.contentful.service"

    nglayouts_contentful:
        alias: netgen_layouts.contentful.controller.contenful
        public: true
