services:
    netgen_layouts.contentful.controller.contenful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Controller\ContentfulController
        public: true
        parent: netgen_block_manager.controller.base
        arguments:
            - "@netgen_layouts.contentful.service"

    nglayouts_contentful:
        alias: netgen_layouts.contentful.controller.contenful
        public: true
