services:
    netgen_layouts.contentful.value_converter.contentful_entry:
        class: Netgen\Layouts\Contentful\Item\ValueConverter\EntryValueConverter
        tags:
            - { name: netgen_block_manager.item.value_converter }

    netgen_layouts.contentful.value_loader.contentful_entry:
        class: Netgen\Layouts\Contentful\Item\ValueLoader\EntryValueLoader
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: netgen_block_manager.item.value_loader, value_type: contentful_entry }
