services:
    netgen_layouts.contentful.layout.resolver.target_type.entry:
        class: Netgen\Layouts\Contentful\Layout\Resolver\TargetType\Entry
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type }

    netgen_layouts.contentful.layout.resolver.form.target_type.mapper.entry:
        class: Netgen\Layouts\Contentful\Layout\Resolver\Form\TargetType\Mapper\Entry
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: contentful_entry }

    netgen_layouts.contentful.layout.resolver.target_handler.doctrine.entry:
        class: Netgen\Layouts\Contentful\Layout\Resolver\TargetHandler\Doctrine\Entry
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: contentful_entry }

    netgen_layouts.contentful.layout.resolver.target_type.space:
        class: Netgen\Layouts\Contentful\Layout\Resolver\TargetType\Space
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type }

    netgen_layouts.contentful.layout.resolver.form.target_type.mapper.space:
        class: Netgen\Layouts\Contentful\Layout\Resolver\Form\TargetType\Mapper\Space
        public: false
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: contentful_space }

    netgen_layouts.contentful.layout.resolver.target_handler.doctrine.space:
        class: Netgen\Layouts\Contentful\Layout\Resolver\TargetHandler\Doctrine\Space
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: contentful_space }

    netgen_layouts.contentful.layout.resolver.condition_type.content_type:
        class: Netgen\Layouts\Contentful\Layout\Resolver\ConditionType\ContentType
        public: false
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_layouts.contentful.layout.resolver.form.condition_type.mapper.content_type:
        class: Netgen\Layouts\Contentful\Layout\Resolver\Form\ConditionType\Mapper\ContentType
        public: false
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: contentful_content_type }
