services:
    netgen_block_manager.contentful.layout.resolver.target_type.entry:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\TargetType\Entry
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type }

    netgen_block_manager.contentful.layout.resolver.form.target_type.mapper.entry:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\Form\TargetType\Mapper\Entry
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: contentful_entry }

    netgen_block_manager.contentful.persistence.doctrine.layout_resolver.query_handler.target_handler.entry:
        class: Netgen\BlockManager\Contentful\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Entry
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: contentful_entry }

    netgen_block_manager.contentful.layout.resolver.target_type.space:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\TargetType\Space
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_type }

    netgen_block_manager.contentful.layout.resolver.form.target_type.mapper.space:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\Form\TargetType\Mapper\Space
        public: false
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.target_type.mapper, target_type: contentful_space }

    netgen_block_manager.contentful.persistence.doctrine.layout_resolver.query_handler.target_handler.space:
        class: Netgen\BlockManager\Contentful\Persistence\Doctrine\QueryHandler\LayoutResolver\TargetHandler\Space
        public: false
        tags:
            - { name: netgen_block_manager.persistence.doctrine.layout_resolver.query_handler.target_handler, target_type: contentful_space }

    netgen_block_manager.contentful.layout.resolver.condition_type.content_type:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\ConditionType\ContentType
        public: false
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.condition_type }

    netgen_block_manager.contentful.layout.resolver.form.condition_type.mapper.content_type:
        class: Netgen\BlockManager\Contentful\Layout\Resolver\Form\ConditionType\Mapper\ContentType
        public: false
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            - { name: netgen_block_manager.layout.resolver.form.condition_type.mapper, condition_type: contentful_content_type }
