services:
    netgen_block_manager.contentful.collection.query_type.handler.contentful_search:
        class: Netgen\BlockManager\Contentful\Collection\QueryType\Handler\ContentfulHandler
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            - { name: netgen_block_manager.collection.query_type_handler, type: contentful_search }
