services:
    netgen_layouts.contentful.routing.enhancer:
        class: Netgen\Layouts\Contentful\Routing\ContentfulEnhancer
        public: true
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            -  { name: dynamic_router_route_enhancer, priority: 10 }
