services:
    netgen_block_manager.contentful.routing.enhancer:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Routing\ContentfulEnhancer
        public: true
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            -  { name: dynamic_router_route_enhancer, priority: 10 }
