services:
    netgen_block_manager.contentful.service:
        class: Netgen\BlockManager\Contentful\Service\Contentful
        public: true
        arguments:
            - []
            - "@contentful.delivery"
            - "@doctrine.orm.entity_manager"
            - "@filesystem"
            - "%netgen_block_manager.contentful.cache_dir%"

    netgen_block_manager.contentful.command.sync:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Command\SyncCommand
        # public: false
        arguments:
              - "@netgen_block_manager.contentful.service"
              - "@filesystem"
        tags:
              - { name: console.command, command: contentful:sync }
