services:
    netgen_block_manager.contentful.service:
        class: Netgen\BlockManager\Contentful\Service\Contentful
        public: true
        arguments:
            - []
            - "@netgen_block_manager.contentful.entry_slugger.configurable"
            - "@contentful.delivery"
            - "@doctrine.orm.entity_manager"
            - "@filesystem"
            - "%netgen_block_manager.contentful.cache_dir%"

    netgen_block_manager.contentful.command.sync:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Command\SyncCommand
        # public: false
        arguments:
              - "@netgen_block_manager.contentful.service"
              - "@filesystem"
        tags:
              - { name: console.command, command: contentful:sync }

    netgen_block_manager.contentful.entry_slugger.configurable:
        class: Netgen\BlockManager\Contentful\Routing\EntrySlugger\Configurable
        public: false
        arguments:
            - "%netgen_block_manager.contentful.entry_slug_type%"
            - []

    netgen_block_manager.contentful.entry_slugger.simple:
        class: Netgen\BlockManager\Contentful\Routing\EntrySlugger\Simple
        public: false
        tags:
            - { name: netgen_block_manager.contentful.entry_slugger, type: simple }

    netgen_block_manager.contentful.entry_slugger.with_space:
        class: Netgen\BlockManager\Contentful\Routing\EntrySlugger\WithSpace
        public: false
        tags:
            - { name: netgen_block_manager.contentful.entry_slugger, type: with_space }
