services:
    netgen_block_manager.contentful.service:
        class: Netgen\BlockManager\Contentful\Service\Contentful
        public: true
        arguments:
            - "%contentful.clients%"
            - "@service_container"
            - "@doctrine.orm.entity_manager"

    netgen_block_manager.contentful.command.sync:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Command\SyncCommand
        # public: false
        arguments:
              - "@netgen_block_manager.contentful.service"
              - "%contentful.clients%"
        tags:
              - { name: console.command, command: contentful:sync }
