services:
    netgen_block_manager.contentful.service:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Service\Contentful
        arguments:
            - "%contentful.clients%"
            - "@service_container"
            - "@doctrine.orm.entity_manager"
        public: true

    netgen_block_manager.contentful.sync_command:
        class: Netgen\Bundle\ContentfulBlockManagerBundle\Command\SyncCommand
        arguments:
              - "@netgen_block_manager.contentful.service"
        public: true
        tags:
              - { name: console.command }

