services:
    netgen_layouts.contentful.templating.twig.extension.contentful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Templating\Twig\Extension\ContentfulExtension
        public: false
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: twig.extension }

    netgen_layouts.contentful.templating.twig.runtime.contentful:
        class: Netgen\Bundle\LayoutsContentfulBundle\Templating\Twig\Runtime\ContentfulRuntime
        # public: false
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }

    netgen_layouts.contentful.templating.twig.extension.markdown.engine:
        class: Aptoma\Twig\Extension\MarkdownEngine\MichelfMarkdownEngine
        public: false

    netgen_layouts.contentful.templating.twig.extension.markdown:
        class: Aptoma\Twig\Extension\MarkdownExtension
        public: false
        arguments:
            - "@netgen_layouts.contentful.templating.twig.extension.markdown.engine"
        tags:
            - { name: twig.extension }
