view:
    block_view:
        default:
            contentful_entry_field:
                template: "@NetgenContentfulBlockManager/ngbm/block/contentful_entry_field.html.twig"
                match:
                    block\definition: contentful_entry_field
                    block\view_type: contentful_entry_field
        api:
            contentful_entry_field:
                template: "@NetgenContentfulBlockManager/ngbm/block/api/contentful_entry_field.html.twig"
                match:
                    block\definition: contentful_entry_field
