view:
    block_view:
        default:
            contentful_entry_field:
                template: "@nglayouts/block/contentful_entry_field.html.twig"
                match:
                    block\definition: contentful_entry_field
                    block\view_type: contentful_entry_field
        app:
            contentful_entry_field:
                template: "@NetgenLayoutsContentful/app/block/contentful_entry_field.html.twig"
                match:
                    block\definition: contentful_entry_field
