view:
    item_view:
        default:
            contentful_entry:
                template: "@nglayouts/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        ajax:
            contentful_entry:
                template: "@nglayouts/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        api:
            contentful_entry:
                template: "@NetgenLayoutsContentful/api/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
