view:
    item_view:
        default:
            contentful_entry:
                template: "@NetgenContentfulBlockManager/ngbm/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        ajax:
            contentful_entry:
                template: "@NetgenContentfulBlockManager/ngbm/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
        api:
            contentful_entry:
                template: "@NetgenContentfulBlockManager/ngbm/item/contentful_entry.html.twig"
                match:
                    item\value_type: contentful_entry
