view:
    rule_condition_view:
        value:
            contentful_content_type:
                template: "@NetgenContentfulBlockManager/admin/layout_resolver/condition/value/contentful_content_type.html.twig"
                match:
                    rule_condition\type: contentful_content_type
