item_types:
    contentful_entry:
        name: item_types.contentful_entry
        preview:
            template: '@NetgenContentfulBlockManager/browser/contentful_entry.html.twig'
        columns:
            name:
                name: columns.name
                value_provider: name
            content_type:
                name: columns.contentful_entry.content_type
                value_provider: contentful_entry\content_type
            created_at:
                name: columns.contentful_entry.created_at
                value_provider: contentful_entry\created_at
            updated_at:
                name: columns.contentful_entry.updated_at
                value_provider: contentful_entry\updated_at
        default_columns:
            - name
            - content_type
