services:
    netgen_layouts.contentful.browser.backend:
        class: Netgen\Layouts\Contentful\Browser\Backend\ContentfulBackend
        arguments:
            - "@netgen_layouts.contentful.service"
        tags:
            -  { name: netgen_content_browser.backend, item_type: contentful_entry }

    netgen_layouts.contentful.browser.column_value_provider.entry.created_at:
        class: Netgen\Layouts\Contentful\Browser\Item\ColumnProvider\Entry\CreatedAt
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\created_at }

    netgen_layouts.contentful.browser.column_value_provider.entry.updated_at:
        class: Netgen\Layouts\Contentful\Browser\Item\ColumnProvider\Entry\UpdatedAt
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\updated_at }

    netgen_layouts.contentful.browser.column_value_provider.entry.content_type:
        class: Netgen\Layouts\Contentful\Browser\Item\ColumnProvider\Entry\ContentType
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\content_type }
