services:
    netgen_block_manager.contentful.content_browser.backend.contentful_entry:
        class: Netgen\BlockManager\Contentful\Browser\Backend\ContentfulBackend
        public: false
        arguments:
            - "@netgen_block_manager.contentful.service"
        tags:
            -  { name: netgen_content_browser.backend, item_type: contentful_entry }

    netgen_block_manager.contentful.content_browser.template_value_provider.contentful_entry.created_at:
        class: Netgen\BlockManager\Contentful\Browser\Item\Entry\ColumnValueProvider\CreatedAt
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\created_at }

    netgen_block_manager.contentful.content_browser.template_value_provider.contentful_entry.updated_at:
        class: Netgen\BlockManager\Contentful\Browser\Item\Entry\ColumnValueProvider\UpdatedAt
        public: false
        arguments:
            - "%netgen_content_browser.columns.date_format%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\updated_at }

    netgen_block_manager.contentful.content_browser.template_value_provider.contentful_entry.content_type:
        class: Netgen\BlockManager\Contentful\Browser\Item\Entry\ColumnValueProvider\ContentType
        public: false
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: contentful_entry\content_type }
