block_definitions:
    contentful_entry_field:
        name: 'Contentful entry field'
        icon: '/bundles/netgenlayoutscontentful/icons/block/contentful_entry_field.svg'
        view_types:
            contentful_entry_field_string:
                name: 'String'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_number:
                name: 'Number'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_json:
                name: 'JSON'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_markdown:
                name: 'Markdown'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_richtext:
                name: 'Richtext'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_datetime:
                name: 'Date & time'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'date_format'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_map:
                name: 'Map'
                valid_parameters:
                    - 'field_identifier'
                    - 'zoom'
                    - 'map_type'
                    - 'show_marker'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_assets:
                name: 'Referenced assets'
                valid_parameters:
                    - 'field_identifier'
                    - 'width'
                    - 'height'
                    - 'css_id'
                    - 'css_class'
            contentful_entry_field_entries:
                name: 'Referenced entries'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
