block_definitions:
    contentful_entry_field:
        name: 'Contentful entry field'
        icon: '/bundles/netgenlayoutscontentful/icons/block/contentful_entry_field.svg'
        view_types:
            string:
                name: 'String'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            number:
                name: 'Number'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            json:
                name: 'JSON'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            markdown:
                name: 'Markdown'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            richtext:
                name: 'Richtext'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            datetime:
                name: 'Date & time'
                valid_parameters:
                    - 'field_identifier'
                    - 'html_element'
                    - 'datetime_format'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            map:
                name: 'Map'
                valid_parameters:
                    - 'field_identifier'
                    - 'zoom'
                    - 'map_type'
                    - 'show_marker'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            assets:
                name: 'Referenced assets'
                valid_parameters:
                    - 'field_identifier'
                    - 'width'
                    - 'height'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
            entries:
                name: 'Referenced entries'
                valid_parameters:
                    - 'field_identifier'
                    - 'css_id'
                    - 'css_class'
                    - 'set_container'
