security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_NGLAYOUTS_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/bm/(api|app|admin), role: [ROLE_NGLAYOUTS_ADMIN] }
        - { path: ^/cb, role: [ROLE_NGLAYOUTS_ADMIN] }
